export const headKeywords: Array<string> = [
	'trading bot',
	'exchange skins',
	'csgomoney',
	'csmoney',
	'csgo trade bot',
	'csgo trade',
	'csgo trading bot',
	'trading',
	'cs:go',
	'csgo',
	'cs go',
	'counter-strike',
	'global offensive',
	'trade bot',
	'sell skins',
	'cs:go skin bot',
	'skin bot',
	'cs:go key bot',
	'key bot',
	'bot key',
	'cs:go quicksell bot',
	'exchange bot',
	'cs:go exchange bot',
	'cs go money',
	'cs trading',
	'cs bot',
	'cs skins',
	'кс мани',
	'скины',
	'кс мане',
	'кс маня',
	'кс мания',
	'кс скин',
	'скин го',
	'кс мани обмен',
	'кс го мани',
	'кс го мане',
	'скины кс го',
	'скины cs go',
	'csgo трейд бот',
	'трейд бот',
	'скин бот',
	'ключ бот',
	'бот обмен',
	'трейдить скины',
	'продать скины',
	'глобальное наступление',
	'продавать скины',
	'скин бот',
	'ключ бот',
	'обмен бот',
	'продать бот',
	'более 5000+',
	'крутые ножи',
	'редкие винтовки',
	'перчатки',
	'стикеры',
	'ключи',
	'сайт для обменов',
	'сайт для покупки',
]

export const bodyKeywords: Array<string> = [
	'sign through steam',
	'sign in through steam',
	'faq',
	'bots',
	'stattrack',
	'souvenir',
	'nametag',
	'stickers',
	'commision',
	'2% bonus',
	'to your steam nickname',
	'our statistics',
	'hide statistics',
	'order by',
	'all exterior',
	'select skins that',
	'return skins back',
	'auto select',
	'smart select',
	'exchanges',
	'all users',
	'new users today',
	'exterior',
	'reset all filters',
	'pro version',
	'войдите через steam',
	'войдите через',
	'боты',
	'самый выгодный',
	'обмен скинов',
	'как провести обмен',
	'войдите через steam',
	'введите ссылка на обмен',
	'подтвердите обмен',
	'продать скины',
	'купить скины',
	'про версия',
	'про-версия',
	'автовыбор',
	'авто выбор',
	'скины',
	'скины с блоком',
	'выберите предметы',
	'хотите обменять',
	'доп. фильтры',
	'инвентарь',
	'все качества',
	'сортировать',
	'поиск..',
	'поиск...',
	'чтобы обменять',
	'свой инвентарь публичным',
	'комиссия',
	'cs:go трейд',
	'cs.money',
	'cs money',
	'bug bounty',
	'как это работает',
	'cs:go',
	'csgo',
	'cs go',
]

export const fakeLoginKeywords: Array<string> = [
	'openid',
	'openid/login',
	'valve corporation',
	'steam commumity',
	'steamcommunity',
	'using your steam account',
	'войти с помощью вашего аккаунта steam',
	'нет аккаунта в steam',
	"don't have a steam account",
	"установить steam",
	"install steam",
	"о steam",
	"about steam",
	"valve_public_path",
	"community.akamai.steamstatic.com"
]
